apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/enoldi/order-platformops.git
    targetRevision: main
    path: gitops/argocd/apps
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true